language: scala
scala:
  - 2.11.11
script:
  - sbt clean scalafmt coverage test coverageReport coverageAggregate makeSite generateReadme
  - git diff --exit-code
after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)

